services:
  model_server:
    image: openvino/model_server:latest
    container_name: model_server
    volumes:
      - ./models:/models
    ports:
      - "9000:9000"  # gRPC port
      - "9001:9001"  # REST port
    command: >
      --model_path /models/model
      --model_name resnet
      --port 9000
      --rest_port 9001
      --log_level DEBUG
